apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wms-ingress
  namespace: nkmk
spec:
  ingressClassName: nginx
  rules:
    - host: wms.gettest.uz
      http:
        paths:
          - backend:
              service:
                name: wms-svc-internal
                port:
                  number: 80
            path: /
            pathType: Prefix
