apiVersion: v1
kind: Service
metadata:
  labels:
    app: wms
  name: wms-svc-internal
  namespace: nkmk
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: wms
  type: ClusterIP
